language: node_js
node_js:
  - '4'
before_script:
  - 'npm install -g @angular/cli'
script:
  - 'ng build'

# Do full build before a deploy.
before_deploy:
  - 'ng build'
deploy:
  - provider: gcs
    access_key_id: $GCS_ACCESS_KEY
    secret_access_key: $GCS_SECRET_ACCESS_KEY
    bucket: "static.roster.housatonicbsa.org"
    skip_cleanup: true
    local_dir: dist/roster-web
    acl: public-read
    cache_control: "private, max-age=0, no-transform"
